matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    nodejs:
    - 8
    - 10
    services:
    - docker
    before_install:
    - "./run_docker.sh"
    script:
    - make lint
    - make test
    - make e2e

  - os: osx
    osx_image: xcode10
    env:
    - CPPFLAGS=-I/usr/local/opt/openssl/include
    - LDFLAGS=-L/usr/local/opt/openssl/lib
    before_install:
    - brew install openssl
    nodejs:
    - 4
    - 6
    script:
    - make lint
    - make test
    - make check
language: node_js
cache:
  directories:
  - node_modules

deploy:
  provider: script
  script: npx prebuild -t 8.0.0 -t 9.0.0 -t 10.0.0 --all --strip -u $AUTH_TOKEN
  skip_cleanup: true
  on:
    tags: true
